components:
    schemas:
        Country:
            properties:
                a2:
                    pattern: "[A-Z]{2}"
                    type: string
                a3:
                    pattern: "[A-Z]{3}"
                    type: string
                active:
                    default: true
                    type: boolean
                billingAllowed:
                    default: true
                    type: boolean
                groupFilterEnabled:
                    default: false
                    type: boolean
                id:
                    format: int64
                    readOnly: true
                    type: integer
                idd:
                    type: integer
                name:
                    type: string
                number:
                    type: integer
                position:
                    default: 0.0
                    format: double
                    type: number
                regions:
                    items:
                        $ref: "#/components/schemas/Region"
                    readOnly: true
                    type: array
                shippingAllowed:
                    default: true
                    type: boolean
                subjectToVAT:
                    default: false
                    type: boolean
                title_i18n:
                    additionalProperties:
                        type: string
                    type: object
                zipRequired:
                    default: true
                    type: boolean
            required:
                - a2
                - a3
                - name
                - number
            type: object
        Region:
            properties:
                active:
                    default: true
                    type: boolean
                countryId:
                    format: int64
                    type: integer
                id:
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    type: string
                regionCode:
                    type: string
                title_i18n:
                    additionalProperties:
                        type: string
                    type: object
            required:
                - regionCode
                - name
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.headless.admin.address.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Headless Admin Address"
    version: v1.0
openapi: 3.0.1
paths:
    "/countries":
        get:
            operationId: getCountriesPage
            parameters:
                - in: query
                  name: active
                  schema:
                      type: boolean
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Country"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Country"
                                type: array
            tags: ["Country"]
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Country"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Country"
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Country"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Country"
            tags: ["Country"]
    "/countries/by-a2/{a2}":
        get:
            operationId: getCountryByA2
            parameters:
                - in: path
                  name: a2
                  required: true
                  schema:
                      pattern: "[A-Z]{2}"
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Country"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Country"
            tags: ["Country"]
    "/countries/by-a3/{a3}":
        get:
            operationId: getCountryByA3
            parameters:
                - in: path
                  name: a3
                  required: true
                  schema:
                      pattern: "[A-Z]{3}"
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Country"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Country"
            tags: ["Country"]
    "/countries/by-name/{name}":
        get:
            operationId: getCountryByName
            parameters:
                - in: path
                  name: name
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Country"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Country"
            tags: ["Country"]
    "/countries/by-number/{number}":
        get:
            operationId: getCountryByNumber
            parameters:
                - in: path
                  name: number
                  required: true
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Country"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Country"
            tags: ["Country"]
    "/countries/{countryId}":
        get:
            operationId: getCountry
            parameters:
                - in: path
                  name: countryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Country"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Country"
            tags: ["Country"]