components:
    schemas:
        DocumentField:
            properties:
                values:
                    items:
                        type: object
                    type: array
        HighlightField:
            properties:
                fragment_offset:
                    type: integer
                fragment_size:
                    type: integer
                number_of_fragments:
                    type: integer
        Parameter:
            properties:
                dateFormat:
                    type: string
                defaultValueDouble:
                    format: double
                    type: number
                defaultValueFloat:
                    format: float
                    type: number
                defaultValueInteger:
                    type: integer
                defaultValueLong:
                    format: int64
                    type: integer
                defaultValueString:
                    type: string
                defaultValuesIntegerArray:
                    items:
                        type: integer
                    type: array
                defaultValuesLongArray:
                    items:
                        format: int64
                        type: integer
                    type: array
                defaultValuesStringArray:
                    items:
                        type: string
                    type: array
                maxValueDouble:
                    format: double
                    type: number
                maxValueFloat:
                    format: float
                    type: number
                maxValueInteger:
                    type: integer
                maxValueLong:
                    format: int64
                    type: integer
                minValueDouble:
                    format: double
                    type: number
                minValueFloat:
                    format: float
                    type: number
                minValueInteger:
                    type: integer
                minValueLong:
                    format: int64
                    type: integer
                parameterType:
                    enum: [Date, Double, Float, Integer, IntegerArray, Long, LongArray, String, StringArray, TimeRange]
                    type: string
        SXPBlueprint:
            properties:
                configuration:
                    properties:
                        advanced:
                            properties:
                                excludes:
                                    items:
                                        type: string
                                    type: array
                                includes:
                                    items:
                                        type: string
                                    type: array
                            type: object
                        aggregationConfiguration:
                            properties:
                                aggs:
                                    type: object
                            type: object
                        facet:
                            properties:
                                enabled:
                                    type: boolean
                            type: object
                        general:
                            properties:
                                clauseContributorsExcludes:
                                    items:
                                        type: string
                                    type: array
                                clauseContributorsIncludes:
                                    items:
                                        type: string
                                    type: array
                                emptySearchEnabled:
                                    type: boolean
                                explain:
                                    type: boolean
                                includeResponseString:
                                    type: boolean
                                searchableAssetTypes:
                                    items:
                                        type: string
                                    type: array
                            type: object
                        highlight:
                            properties:
                                fields:
                                    additionalProperties:
                                        $ref: "#/components/schemas/HighlightField"
                                    type: object
                                fragment_size:
                                    type: integer
                                number_of_fragments:
                                    type: integer
                                post_tags:
                                    items:
                                        type: string
                                    type: array
                                pre_tags:
                                    items:
                                        type: string
                                    type: array
                                require_field_match:
                                    type: boolean
                                type:
                                    type: string
                            type: object
                        parameters:
                            additionalProperties:
                                $ref: "#/components/schemas/Parameter"
                            type: object
                        queryConfiguration:
                            properties:
                                applyIndexerClauses:
                                    type: boolean
                                queryEntries:
                                    items:
                                        properties:
                                            clauses:
                                                items:
                                                    properties:
                                                        context:
                                                            type: string
                                                        occur:
                                                            type: string
                                                        query:
                                                            type: object
                                                    type: object
                                                type: array
                                            enabled:
                                                type: boolean
                                        type: object
                                    type: array
                            type: object
                        sortConfiguration:
                            properties:
                                sorts:
                                    type: object
                            type: object
                    type: object
                description:
                    type: string
                id:
                    format: int64
                    type: integer
                title:
                    type: string
            type: object
        SXPElement:
            properties:
                description:
                    type: string
                id:
                    format: int64
                    type: integer
                title:
                    type: string
            type: object
        SearchRequest:
            properties:
                queryString:
                    type: string
            type: object
        SearchResponse:
            properties:
                documents:
                    items:
                        properties:
                            documentFields:
                                additionalProperties:
                                    $ref: "#/components/schemas/DocumentField"
                                type: object
                            explanation:
                                type: string
                            score:
                                format: double
                                type: number
                        type: object
                    type: array
                maxScore:
                    format: double
                    type: number
                page:
                    type: integer
                pageSize:
                    type: integer
                request:
                    type: object
                requestString:
                    type: string
                response:
                    type: object
                responseString:
                    type: string
                searchRequest:
                    $ref: "#/components/schemas/SearchRequest"
                totalHits:
                    type: integer
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.search.experiences.rest.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: "3.0.1"
paths:
    "/search":
        get:
            operationId: getSearch
            parameters:
                - in: query
                  name: query
                  schema:
                      type: string
                - in: query
                  name: sxpBlueprint
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SearchResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SearchResponse"
            tags: ["SearchResponse"]
    /sxp-blueprints:
        get:
            operationId: getSXPBlueprintsPage
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SXPBlueprint"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SXPBlueprint"
                                type: array
            tags: ["SXPBlueprint"]
        post:
            operationId: postSXPBlueprint
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SXPBlueprint"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SXPBlueprint"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SXPBlueprint"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SXPBlueprint"
            tags: ["SXPBlueprint"]
    /sxp-blueprints/{sxpBlueprintId}:
        delete:
            operationId: deleteSXPBlueprint
            parameters:
                - in: path
                  name: sxpBlueprintId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["SXPBlueprint"]
        get:
            operationId: getSXPBlueprint
            parameters:
                - in: path
                  name: sxpBlueprintId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SXPBlueprint"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SXPBlueprint"
            tags: ["SXPBlueprint"]
        patch:
            operationId: patchSXPBlueprint
            parameters:
                - in: path
                  name: sxpBlueprintId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SXPBlueprint"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SXPBlueprint"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SXPBlueprint"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SXPBlueprint"
            tags: ["SXPBlueprint"]
    /sxp-elements:
        get:
            operationId: getSXPElementsPage
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SXPElement"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SXPElement"
                                type: array
            tags: ["SXPElement"]
        post:
            operationId: postSXPElement
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SXPElement"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SXPElement"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SXPElement"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SXPElement"
            tags: ["SXPElement"]
    /sxp-elements/{sxpElementId}:
        delete:
            operationId: deleteSXPElement
            parameters:
                - in: path
                  name: sxpElementId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["SXPElement"]
        get:
            operationId: getSXPElement
            parameters:
                - in: path
                  name: sxpElementId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SXPElement"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SXPElement"
            tags: ["SXPElement"]
        patch:
            operationId: patchSXPElement
            parameters:
                - in: path
                  name: sxpElementId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SXPElement"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SXPElement"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SXPElement"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SXPElement"
            tags: ["SXPElement"]