components:
    schemas:
        ObjectEntry:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                creator:
                    allOf:
                        - $ref: "../../headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml#Creator"
                    readOnly: true
                dateCreated:
                    format: date
                    type: string
                dateModified:
                    format: date
                    type: string
                externalReferenceCode:
                    readOnly: true
                    type: string
                id:
                    format: int64
                    type: integer
                properties:
                    additionalProperties:
                        type: object
                    type: object
                    x-json-map: true
                scopeKey:
                    readOnly: true
                    type: string
                status:
                    $ref: "#/components/schemas/Status"
                    readOnly: true
            type: object
        Status:
            properties:
                code:
                    format: int32
                    readOnly: true
                    type: integer
                label:
                    type: string
                label_i18n:
                    type: string
            type: object
info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Object"
    version: v1.0
openapi: 3.0.1
paths:
    "":
        get:
            operationId: getObjectEntriesPage
            parameters:
                - in: query
                  name: aggregationTerms
                  schema:
                      items:
                          type: string
                      type: array
                - in: query
                  name: flatten
                  schema:
                      type: boolean
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
                - in: header
                  name: Accept-Language
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ObjectEntry"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ObjectEntry"
                                type: array
            tags: ["ObjectEntry"]
        post:
            operationId: postObjectEntry
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
    "/by-external-reference-code/{externalReferenceCode}":
        delete:
            operationId: deleteByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["ObjectEntry"]
        get:
            operationId: getByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
        put:
            operationId: putByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
    "/scopes/{scopeKey}/by-external-reference-code/{externalReferenceCode}":
        delete:
            operationId: deleteScopeScopeKeyByExternalReferenceCode
            parameters:
                - in: path
                  name: scopeKey
                  required: true
                  schema:
                      type: string
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["ObjectEntry"]
        get:
            operationId: getScopeScopeKeyByExternalReferenceCode
            parameters:
                - in: path
                  name: scopeKey
                  required: true
                  schema:
                      type: string
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
        put:
            operationId: putScopeScopeKeyByExternalReferenceCode
            parameters:
                - in: path
                  name: scopeKey
                  required: true
                  schema:
                      type: string
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
    "/{objectEntryId}":
        delete:
            operationId: deleteObjectEntry
            parameters:
                - in: path
                  name: objectEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["ObjectEntry"]
        get:
            operationId: getObjectEntry
            parameters:
                - in: path
                  name: objectEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
        patch:
            operationId: patchObjectEntry
            parameters:
                - in: path
                  name: objectEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
        put:
            operationId: putObjectEntry
            parameters:
                - in: path
                  name: objectEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]
    /scopes/{scopeKey}:
        get:
            operationId: getScopeScopeKeyPage
            parameters:
                - in: path
                  name: scopeKey
                  schema:
                      type: string
                - in: query
                  name: aggregationTerms
                  schema:
                      items:
                          type: string
                      type: array
                - in: query
                  name: flatten
                  schema:
                      type: boolean
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
                - in: header
                  name: Accept-Language
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ObjectEntry"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ObjectEntry"
                                type: array
            tags: ["ObjectEntry"]
        post:
            operationId: postScopeScopeKey
            parameters:
                - in: path
                  name: scopeKey
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ObjectEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectEntry"
            tags: ["ObjectEntry"]